### ISSUE TITLE
Error con hibernate usando docker JAR

### ISSUE THREAD

**Issue by zamudio-fabian** [CodelyTV/cqrs-ddd-java-example#20]
### Descripción

Estoy comenzando a aplicar DDD en un proyecto ya funcional. Hasta el momento logre hacer funcionar correctamente una simple búsqueda de datos en la BD implementado la abstracción de hibernate usando los archivo hbm.xml.

Al momento de intentar ejecutar el mismo en docker el mismo falla al buscar los resultados de la BD con el siguiente error:

```
company-notification | 2021-02-19 18:04:18.636 ERROR 1 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.remax.notification.aggregates.shared.domain.bus.query.QueryHandlerExecutionError: java.lang.IllegalArgumentException: Not an entity: class com.company.notification.aggregates.notification_type.domain.NotificationType] with root cause
company-notification | java.lang.IllegalArgumentException: Not an entity: class com.company.notification.aggregates.notification_type.domain.NotificationType
company-notification | at org.hibernate.metamodel.internal.MetamodelImpl.entity(MetamodelImpl.java:566) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
company-notification | at org.hibernate.query.criteria.internal.QueryStructure.from(QueryStructure.java:127) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
company-notification | at org.hibernate.query.criteria.internal.CriteriaQueryImpl.from(CriteriaQueryImpl.java:154) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
```

### Posible causa

Estoy casi seguro que es por debido a la función searchMappingFiles que no encuentra los archivos de definición y al recuperar no encuentra una entidad para tales datos.

### Config

DockerFile
```
FROM amazoncorretto:11
VOLUME /tmp
COPY build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```

**Comment by zamudio-fabian** [comment]
Se mueve la consulta al proyecto de skeleton https://github.com/CodelyTV/java-ddd-skeleton/issues/67

**Comment by r2d2f** [comment]
La verdad que a mi nunca me funcionó el searchMappingFiles cuando exporto como un jar. 

Solo funciona cuando usas en el IDE... El tema es que la estructura de directorios es distinta cuando se empaqueta en un jar, no es la misma que cuando corres la aplicacion desde el IDE.

Yo solucione parcialmente eso (hacia mi casa se llama, alambre) especificando directamente los archivos del Mapping, sin usar el searchMappingFiles. No me dio el tiempo arreglarlo bien realmente.
